### ISSUE TITLE
yolov7-tiny-obb训练数据集

### ISSUE THREAD

**Issue by cjx1770702668** [Egrt/yolov7-tiny-obb#1]
我想用博主该代码直接训练康奈尔数据集，康奈尔数据集原始标签是旋转框的四个点的坐标（x，y），我直接按照2007_train.txt文件的格式生成训练用的cornell.txt文件，即生成图片路径和八个坐标一组的信息。下面是原始图片、标注的图片的样式和生成的cornell.txt文件，没有类别信息，我就直接开始训练，结果遇到了这个问题，请问一下该怎么解决呀！
![image](https://user-images.githubusercontent.com/126368697/221390440-6bb8fd58-7f8a-4d3a-bd9d-8e50d6166290.png)

![pcd0100r](https://user-images.githubusercontent.com/126368697/221390265-48f9d5fe-ab65-4ebd-9fce-d5f6329f1a1a.jpg)
![pcd0100r](https://user-images.githubusercontent.com/126368697/221390308-bd5b0731-a8f9-4a6e-865a-8d0bbd40d899.png)
[cornell.txt](https://github.com/Egrt/yolov7-tiny-obb/files/10832861/cornell.txt)

**Comment by Egrt** [comment]
是不是没有修改coco_classes.txt中的类别数，仔细阅读redme的说明，需要修改类别txt

**Comment by cjx1770702668** [comment]
> 是不是没有修改coco_classes.txt中的类别数，仔细阅读redme的说明，需要修改类别txt
嗯嗯，改好了，谢谢提醒，原因就是我写的txt文件的类别没加上。

**Comment by cjx1770702668** [comment]
> 是不是没有修改coco_classes.txt中的类别数，仔细阅读redme的说明，需要修改类别txt
嗯嗯，改好了，谢谢提醒，原因就是我写的txt文件的类别没加上。
