### ISSUE TITLE
Question about how you evaluate 

### ISSUE THREAD

**Issue by VietPT3502** [Egrt/yolov7-tiny-obb#2]
does ur mAP is HBBmAP or OBBmAP

**Comment by Egrt** [comment]
> does ur mAP is HBBmAP or OBBmAP

It is HBBmAP. You can also modify the code to calculate OBBmAP by yourself.

**Comment by VietPT3502** [comment]
I got this message when change batch-size to 8 when re-train UAV-ROD dataset.
[Warning] 使用adam优化器时，建议将训练总步长设置到15000以上。
[Warning] 本次运行的总训练数据量为1150，Unfreeze_batch_size为8，共训练100个Epoch，计算出总训练步长为14300。
[Warning] 由于总训练步长为14300，小于建议总步长15000，建议设置总世代为105。
Which i understand but i want to ask why u are using Adam instead of SGD because Adam often performance worse than SGD in image problems. What if im using SGD, will performance will become worse ? and which parameters will affect my training ?

**Comment by Egrt** [comment]
> I got this message when change batch-size to 8 when re-train UAV-ROD dataset. [Warning] 使用adam优化器时，建议将训练总步长设置到15000以上。 [Warning] 本次运行的总训练数据量为1150，Unfreeze_batch_size为8，共训练100个Epoch，计算出总训练步长为14300。 [Warning] 由于总训练步长为14300，小于建议总步长15000，建议设置总世代为105。 Which i understand but i want to ask why u are using Adam instead of SGD because Adam often performance worse than SGD in image problems. What if im using SGD, will performance will become worse ? and which parameters will affect my training ?

I give the suggested parameters for training using Adam or SGD in train.py.
SGD.
    # Init_Epoch = 0, Freeze_Epoch = 50, UnFreeze_Epoch = 300, Freeze_Train = True, optimizer_type = 'sgd', Init_lr = 1e-2, weight_decay = 5e-4. (Freeze)
    # Init_Epoch = 0, UnFreeze_Epoch = 300, Freeze_Train = False, optimizer_type = 'sgd', Init_lr = 1e-2, weight_decay = 5e-4. (Not frozen)

**Comment by VietPT3502** [comment]
tks for the fast reply. That's really help

**Comment by Egrt** [comment]
> tks for the fast reply. That's really help

😊(●'◡'●)
