### ISSUE TITLE
re-load dataset after 1 epoch

### ISSUE THREAD

**Issue by trand2k** [Egrt/yolov7-tiny-obb#3]
hi, guy
why line 531 in train.py file need re-load dataset per epoch? It already load in line 478. any trick for this?

**Comment by Egrt** [comment]
> hi, guy why line 531 in train.py file need re-load dataset per epoch? It already load in line 478. any trick for this?

The first part of the training is for the first 50 epochs, which freezes the backbone network and updates only the parameters of the FPN and YOLO Head. The latter part of the training is for 50 to 100 epochs, which updates the full parameters of the model, which can be translated into English by reading my notes in 'train.py'.
