### ISSUE TITLE
【矩形输入】修改输入分辨率为矩形（32的倍数），Recall急速下降

### ISSUE THREAD

**Issue by Eric-luckxt** [Egrt/yolov7-tiny-obb#7]
Hi，使用时发现仅修改分辨率（640 640）->(960,512)，使用640*640的模型为预训练模型，Recall降的很低（不到50%）

排查后发现yolo_training.py中（251行），build_targets函数，对真实框的坐标进行缩放的位置，

txywh = this_target[:, 2:6] * imgs[batch_idx].shape[1]应该是错误的，相当于xywh全部乘了图像高？应该是不对的

修改为xw yh分别乘图像宽高后训练，看起来结果正常

**Comment by Egrt** [comment]
> Hi，使用时发现仅修改分辨率（640 640）->(960,512)，使用640*640的模型为预训练模型，Recall降的很低（不到50%）
> 
> 排查后发现yolo_training.py中（251行），build_targets函数，对真实框的坐标进行缩放的位置，
> 
> txywh = this_target[:, 2:6] * imgs[batch_idx].shape[1]应该是错误的，相当于xywh全部乘了图像高？应该是不对的
> 
> 修改为xw yh分别乘图像宽高后训练，看起来结果正常

是的，一开始没有考虑到非正方形图像的输入。
